services:
  database:
    container_name: "postgres-dev"
    image: "postgres:18-alpine3.22"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"

  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1090:1080"
